### ISSUE TITLE
Hauptpunkt: "Installationsanleitung"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.docs#13]
Aufteilung nach "Fertige Images" (Zielgruppe Dau und Normalo) und "Manual Install" (für eher "wissende" mit ggf Unterbereichen für allgemeine Voraussetzungen und je Betriebssystem Linux, Windows, macOS, Andere, gff NAS o.ä. ggf auch Forum Links zu Threads für spezifischere Fälle

Ein "Installation Troubleshooting" Bereich im FAQ Style?

**Comment by stabilostick** [comment]
Replaced by #50
