### ISSUE TITLE
Abschnitt 'Impressum'

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.docs#137]
Erstellen des Inhalts für diesen Dokumentationsabschnitt.

**Comment by Apollon77** [comment]
@GermanBluefox Bitte mal reviewen ob das so korrekt ist oder was zu ändern ist ...

**Comment by Jey-Cee** [comment]
Ist jetzt 2 Jahre alt und das Impressum schon lange auf der Webseite, dürfte also als erledigten angesehen werden oder?
