### ISSUE TITLE
Hauptpunkt "Erste Schritte" (nach Installation)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.docs#15]
Tutorial Step-by-Step mit Zielgruppe "Erstnutzer".

Einmal durch die UI führen und Überblick geben, eher noch keine Adapter ?!

Was heissen die einzelnen Tabs im Admin? Was sehe ich dort, Die "Buttons" dort kurz erklärt

**Comment by stabilostick** [comment]
Replaced by #76
