### ISSUE TITLE
Installationsanleitung nicht genau.

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.docs#26]
Nachrichtentext:
einen schönen guten Abend wünsche ich Ihnen,
diese Anleitung funktioniert von vorne bis hinten nicht. Sollte mal dringend überarbeitet werden.
http://www.iobroker.net/docu/?page_id=5358&lang=de

MfG

xxx yyy

root@debian:~# apt-get install update
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket update kann nicht gefunden werden.
root@debian:~# aptitude install sudo
bash: aptitude: Kommando nicht gefunden.
root@debian:~# apt-get install npm
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket npm kann nicht gefunden werden.
root@debian:~#

**Comment by stabilostick** [comment]
Replaced by #54
