### ISSUE TITLE
Object type `info` is missing from objectsschema.md

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.docs#274]
Apparently, it exists in ioBroker:
![grafik](https://user-images.githubusercontent.com/17641229/99284003-07d9ee80-2836-11eb-8237-6fa1749ed6bb.png)

Although it affects only a single object, maybe it should get a different type?
![grafik](https://user-images.githubusercontent.com/17641229/99284249-4d96b700-2836-11eb-9ade-7ca8fb2a0aa6.png)

**Comment by Apollon77** [comment]
hehe ... hm ...

**Comment by GermanBluefox** [comment]
Fixed long time ago in socketio. "info" is not valid object type:
![image](https://user-images.githubusercontent.com/4582016/100002852-746c6480-2dc5-11eb-9a84-254d391e7436.png)

**Comment by AlCalzone** [comment]
Heh, guess this how old my installation is now 😅
