### ISSUE TITLE
Installation inside docker container does not work

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.docs#277]
I have serious problems with my installation inside a docker container. The main problem is, that on every update of a adapter, the rest of the installation is destroyed in a way that the adapters continuous needs reinstalling. See one sample in screenshot. To get the system running stable the only way is to execute the reinstall.js script, but then all the adapters are again on the previous version. 
<img width="1021" alt="Screenshot 2020-11-19 at 23 57 05" src="https://user-images.githubusercontent.com/35381530/99734355-fb1dfa80-2ac2-11eb-9c0f-3674c8acf5da.png">

Is there any idea what could cause such behaviour and how to solve this?

here a complete log of the reinstall.js log created [2020-11-19T23_36_15_330Z-debug.log](https://github.com/ioBroker/ioBroker.docs/files/5570331/2020-11-19T23_36_15_330Z-debug.log)

**Comment by Apollon77** [comment]
WHich docker container is used? Please open the issue there ... this is the docs project for the iobroker documentation

**Comment by nkleber78** [comment]
Hallo Apollon,
auch wenn ich nicht glaube dass der Docker das problem ist, werde ich es mal dort versuchen. Entschuldige dass ich hier das falsche projekt erwischt habe, doku relevant ist das natürlich nicht.
