### ISSUE TITLE
Decimal comma missing in Alias example

### ISSUE THREAD

**Issue by Videonisse** [ioBroker/ioBroker.docs#300]
In the example for "Seit Version 3.0 des js-controllers können getrennte Status- und Kommando-Datenpunkte im Alias zusammengeführt werden:"

It should be:

                write: 'state.id.to.write.to'
            },
Currently it says (complete example):
`{
    _id: "alias.0.aliasName",
    common: {
        name: 'Test AliasC',
        type: 'number',
        role: 'state',
        min: -10,
        max: 10,
        alias: {
            id: {
                read: 'state.id.to.read.from',
                write: 'state.id.to.write.to'
            }
            read: 'val * 10 + 1',
            write: '(val - 1) / 10'
        }
    },
    native: {},
    type: 'state'
}`

https://www.iobroker.net/#de/documentation/dev/aliases.md

**Comment by Apollon77** [comment]
fixed
