### ISSUE TITLE
Synology Adapter Admin 5 Infomeldungen

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.docs#323]
Hallo zusammen,
leider scheint es keine Github Page des Synology Adapters zu geben, weswegen ich den Issue hier aufmachen wollte. Ist das soweit richtig, oder wie soll ich mich verhalten?

Generell bekomme ich seit Admin 5 folgende Meldung unentwegt:

`State value to set for "synology.0.DiskStationManager.info.uptime" has to be type "string" but received type "number" `

Ich denke es ist Sache des Adapters dies zu ändern, oder?

Vielen Dank für eure Hilfe! :)

**Comment by Apollon77** [comment]
Das issue wäre in dem Projekt richtig ... https://github.com/iobroker-community-adapters/ioBroker.synology

**Comment by DcFamas** [comment]
Oh okay, dachte das wäre tot. Weil der Link von Google nicht geht:
https://github.com/instalator/ioBroker.synology/issues

& der im ioBroker auch nicht über das Fragezeichen.
Werde das entsprechend mitteilen, danke für den Link!
