### ISSUE TITLE
"no existing object, this might lead to an error..."

### ISSUE THREAD

**Issue by Madaraxa** [ioBroker/ioBroker.docs#332]
I get following warnings. I dont use this particular device in any scripts, etc. But it is connected to my fritzbox.

`tr-064.0 | 2021-11-02 04:04:11.267 | warn | State "tr-064.0.devices.RCTPowerstorage" has no existing object, this might lead to an error in future versions
tr-064.0 | 2021-11-02 04:04:11.265 | warn | State "tr-064.0.devices.RCTPowerstorage.lastInactive-ts" has no existing object, this might lead to an error in future versions
tr-064.0 | 2021-11-02 04:04:11.263 | warn | State "tr-064.0.devices.RCTPowerstorage.lastInactive" has no existing object, this might lead to an error in future versions
tr-064.0 | 2021-11-02 04:04:11.255 | warn | State "tr-064.0.devices.RCTPowerstorage.active" has no existing object, this might lead to an error in future versions`

**Comment by Apollon77** [comment]
Please open this issue in the tr-064 adapter repository and update the adapter before to latest verison
