### ISSUE TITLE
[Bug]: Firefox. Uncaught (in promise) DOMException: The operation is insecure.

### ISSUE THREAD

**Issue by om2804** [ioBroker/ioBroker.docs#388]
### What happened?

Go to https://www.iobroker.net/#en/documentation/install/README.md
Google Chrome - ok
Firefox - empty page

![изображение](https://user-images.githubusercontent.com/2576620/173247088-9a3c612d-23ce-4336-8f8d-9baadff31a88.png)

### Link

https://www.iobroker.net/#en/documentation/install/README.md

### Relevant log output

```shell
Uncaught (in promise) DOMException: The operation is insecure.  [main.6523234a.chunk.js:2](https://www.iobroker.net/static/js/main.6523234a.chunk.js)
```

**Comment by oelison** [comment]
Can't reproduce this error.

**Comment by om2804** [comment]
Hm, in private window its ok
